"""Added exchange rates

Revision ID: 0e828a5ac2a3
Revises: f96362a7015d
Create Date: 2025-02-19 20:00:10.178913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e828a5ac2a3'
down_revision = 'f96362a7015d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('exchange_rates_last_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rates_last_update')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
