"""empty message

Revision ID: 680502682745
Revises: 5f59c5a8ce9d
Create Date: 2025-01-19 18:49:28.097811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680502682745'
down_revision = '5f59c5a8ce9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
