"""Added fee to transactions

Revision ID: 7b847b908fa7
Revises: d36f997fc86c
Create Date: 2025-03-09 11:11:11.450536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b847b908fa7'
down_revision = 'd36f997fc86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee', sa.Numeric(precision=15, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('fee')

    # ### end Alembic commands ###
