"""Added PIN column & terminals table

Revision ID: 8606bbdf7eeb
Revises: 358a1e00ea11
Create Date: 2024-09-24 17:41:21.113430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8606bbdf7eeb'
down_revision = '358a1e00ea11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terminal_id')
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfid_code', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('pin', sa.String(length=4), nullable=False))
        batch_op.drop_constraint('card_card_rfid_code_key', type_='unique')
        batch_op.create_unique_constraint(None, ['rfid_code'])
        batch_op.drop_column('card_rfid_code')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terminal_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'terminal', ['terminal_id'], ['terminal_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('terminal_id')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_rfid_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('card_card_rfid_code_key', ['card_rfid_code'])
        batch_op.drop_column('pin')
        batch_op.drop_column('rfid_code')

    op.drop_table('terminal')
    # ### end Alembic commands ###
